"""English names and stable IDs for the IHO Sea Areas v3 snapshot."""

from __future__ import annotations

import re

# Preserve original IDs so historical links, records and exports stay compatible.
OBSERVED_AREAS = {'North Atlantic Ocean': ('atlantic-north', 'North Atlantic Ocean'),
 'South Atlantic Ocean': ('atlantic-south', 'South Atlantic Ocean'),
 'North Pacific Ocean': ('pacific-north', 'North Pacific Ocean'),
 'South Pacific Ocean': ('pacific-south', 'South Pacific Ocean'),
 'Indian Ocean': ('indian', 'Indian Ocean'),
 'Arctic Ocean': ('arctic', 'Arctic Ocean'),
 'Southern Ocean': ('southern', 'Southern Ocean'),
 'Mediterranean Sea - Western Basin': ('med-west', 'Mediterranean Sea - Western Basin'),
 'Mediterranean Sea - Eastern Basin': ('med-east', 'Mediterranean Sea - Eastern Basin'),
 'North Sea': ('north-sea', 'North Sea'),
 'Baltic Sea': ('baltic', 'Baltic Sea'),
 'Black Sea': ('black', 'Black Sea'),
 'Red Sea': ('red', 'Red Sea'),
 'Caribbean Sea': ('caribbean', 'Caribbean Sea'),
 'Gulf of Mexico': ('gulf-mexico', 'Gulf of Mexico'),
 'Arabian Sea': ('arabian', 'Arabian Sea'),
 'Bay of Bengal': ('bengal', 'Bay of Bengal'),
 'South China Sea': ('south-china', 'South China Sea'),
 'Bering Sea': ('bering', 'Bering Sea'),
 'Tasman Sea': ('tasman', 'Tasman Sea'),
 'Coral Sea': ('coral', 'Coral Sea')}

ADDITIONAL_AREAS = ('Rio de La Plata',
 'Bass Strait',
 'Great Australian Bight',
 'Mozambique Channel',
 'Savu Sea',
 'Timor Sea',
 'Bali Sea',
 'Flores Sea',
 'Solomon Sea',
 'Arafura Sea',
 'Gulf of Boni',
 'Java Sea',
 'Ceram Sea',
 'Bismarck Sea',
 'Banda Sea',
 'Gulf of California',
 'Bay of Fundy',
 'Strait of Gibraltar',
 'Alboran Sea',
 'Gulf of Alaska',
 'Chukchi Sea',
 'Beaufort Sea',
 'Labrador Sea',
 'Hudson Strait',
 'Davis Strait',
 'Baffin Bay',
 'Lincoln Sea',
 'Bristol Channel',
 "Irish Sea and St. George's Channel",
 'Inner Seas off the West Coast of Scotland',
 'Gulf of Aden',
 'Gulf of Oman',
 'Gulf of Aqaba',
 'Persian Gulf',
 'Ionian Sea',
 'Tyrrhenian Sea',
 'Adriatic Sea',
 'Gulf of Suez',
 'Aegean Sea',
 'Sea of Marmara',
 'Singapore Strait',
 'Celebes Sea',
 'Malacca Strait',
 'Sulu Sea',
 'Gulf of Thailand',
 'Eastern China Sea',
 'Seto Naikai or Inland Sea',
 'Philippine Sea',
 'Yellow Sea',
 'Gulf of Riga',
 'Gulf of Finland',
 'Gulf of Bothnia',
 'White Sea',
 'East Siberian Sea',
 'Gulf of Tomini',
 'Makassar Strait',
 'Halmahera Sea',
 'Molukka Sea',
 'The Coastal Waters of Southeast Alaska and British Columbia',
 'Gulf of St. Lawrence',
 'Balearic (Iberian Sea)',
 'Bay of Biscay',
 'Celtic Sea',
 'Hudson Bay',
 'The Northwestern Passages',
 'English Channel',
 'Barentsz Sea',
 'Greenland Sea',
 'Andaman or Burma Sea',
 'Sea of Azov',
 'Japan Sea',
 'Sea of Okhotsk',
 'Kara Sea',
 'Laptev Sea',
 'Kattegat',
 'Laccadive Sea',
 'Skagerrak',
 'Norwegian Sea',
 'Ligurian Sea',
 'Gulf of Guinea')

AREAS = OBSERVED_AREAS | {
    name: ("iho-" + re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-"), name)
    for name in ADDITIONAL_AREAS
}
