"""Names and stable IDs for the IHO Sea Areas v3 snapshot."""

from __future__ import annotations

import re

# Keep the original IDs so historical links and CSVs remain compatible.
OBSERVED_AREAS = {
    "North Atlantic Ocean": ("atlantic-north", "Atlántico norte"),
    "South Atlantic Ocean": ("atlantic-south", "Atlántico sur"),
    "North Pacific Ocean": ("pacific-north", "Pacífico norte"),
    "South Pacific Ocean": ("pacific-south", "Pacífico sur"),
    "Indian Ocean": ("indian", "Océano Índico"),
    "Arctic Ocean": ("arctic", "Océano Ártico"),
    "Southern Ocean": ("southern", "Océano Austral"),
    "Mediterranean Sea - Western Basin": ("med-west", "Mediterráneo occidental"),
    "Mediterranean Sea - Eastern Basin": ("med-east", "Mediterráneo oriental"),
    "North Sea": ("north-sea", "Mar del Norte"),
    "Baltic Sea": ("baltic", "Mar Báltico"),
    "Black Sea": ("black", "Mar Negro"),
    "Red Sea": ("red", "Mar Rojo"),
    "Caribbean Sea": ("caribbean", "Mar Caribe"),
    "Gulf of Mexico": ("gulf-mexico", "Golfo de México"),
    "Arabian Sea": ("arabian", "Mar Arábigo"),
    "Bay of Bengal": ("bengal", "Bahía de Bengala"),
    "South China Sea": ("south-china", "Mar de China Meridional"),
    "Bering Sea": ("bering", "Mar de Bering"),
    "Tasman Sea": ("tasman", "Mar de Tasmania"),
    "Coral Sea": ("coral", "Mar del Coral"),
}

ADDITIONAL_NAMES_ES = {
    "Rio de La Plata": "Río de la Plata",
    "Bass Strait": "Estrecho de Bass",
    "Great Australian Bight": "Gran Bahía Australiana",
    "Mozambique Channel": "Canal de Mozambique",
    "Savu Sea": "Mar de Savu",
    "Timor Sea": "Mar de Timor",
    "Bali Sea": "Mar de Bali",
    "Flores Sea": "Mar de Flores",
    "Solomon Sea": "Mar de Salomón",
    "Arafura Sea": "Mar de Arafura",
    "Gulf of Boni": "Golfo de Boni",
    "Java Sea": "Mar de Java",
    "Ceram Sea": "Mar de Ceram",
    "Bismarck Sea": "Mar de Bismarck",
    "Banda Sea": "Mar de Banda",
    "Gulf of California": "Golfo de California",
    "Bay of Fundy": "Bahía de Fundy",
    "Strait of Gibraltar": "Estrecho de Gibraltar",
    "Alboran Sea": "Mar de Alborán",
    "Gulf of Alaska": "Golfo de Alaska",
    "Chukchi Sea": "Mar de Chukchi",
    "Beaufort Sea": "Mar de Beaufort",
    "Labrador Sea": "Mar del Labrador",
    "Hudson Strait": "Estrecho de Hudson",
    "Davis Strait": "Estrecho de Davis",
    "Baffin Bay": "Bahía de Baffin",
    "Lincoln Sea": "Mar de Lincoln",
    "Bristol Channel": "Canal de Bristol",
    "Irish Sea and St. George's Channel": "Mar de Irlanda y canal de San Jorge",
    "Inner Seas off the West Coast of Scotland": "Mares interiores de Escocia occidental",
    "Gulf of Aden": "Golfo de Adén",
    "Gulf of Oman": "Golfo de Omán",
    "Gulf of Aqaba": "Golfo de Aqaba",
    "Persian Gulf": "Golfo Pérsico",
    "Ionian Sea": "Mar Jónico",
    "Tyrrhenian Sea": "Mar Tirreno",
    "Adriatic Sea": "Mar Adriático",
    "Gulf of Suez": "Golfo de Suez",
    "Aegean Sea": "Mar Egeo",
    "Sea of Marmara": "Mar de Mármara",
    "Singapore Strait": "Estrecho de Singapur",
    "Celebes Sea": "Mar de Célebes",
    "Malacca Strait": "Estrecho de Malaca",
    "Sulu Sea": "Mar de Sulu",
    "Gulf of Thailand": "Golfo de Tailandia",
    "Eastern China Sea": "Mar de China Oriental",
    "Seto Naikai or Inland Sea": "Mar Interior de Seto",
    "Philippine Sea": "Mar de Filipinas",
    "Yellow Sea": "Mar Amarillo",
    "Gulf of Riga": "Golfo de Riga",
    "Gulf of Finland": "Golfo de Finlandia",
    "Gulf of Bothnia": "Golfo de Botnia",
    "White Sea": "Mar Blanco",
    "East Siberian Sea": "Mar de Siberia Oriental",
    "Gulf of Tomini": "Golfo de Tomini",
    "Makassar Strait": "Estrecho de Macasar",
    "Halmahera Sea": "Mar de Halmahera",
    "Molukka Sea": "Mar de las Molucas",
    "The Coastal Waters of Southeast Alaska and British Columbia": "Aguas costeras de Alaska sudoriental y Columbia Británica",
    "Gulf of St. Lawrence": "Golfo de San Lorenzo",
    "Balearic (Iberian Sea)": "Mar Balear",
    "Bay of Biscay": "Golfo de Vizcaya",
    "Celtic Sea": "Mar Céltico",
    "Hudson Bay": "Bahía de Hudson",
    "The Northwestern Passages": "Pasos del Noroeste",
    "English Channel": "Canal de la Mancha",
    "Barentsz Sea": "Mar de Barents",
    "Greenland Sea": "Mar de Groenlandia",
    "Andaman or Burma Sea": "Mar de Andamán",
    "Sea of Azov": "Mar de Azov",
    "Japan Sea": "Mar del Japón",
    "Sea of Okhotsk": "Mar de Ojotsk",
    "Kara Sea": "Mar de Kara",
    "Laptev Sea": "Mar de Láptev",
    "Kattegat": "Kattegat",
    "Laccadive Sea": "Mar de Laquedivas",
    "Skagerrak": "Skagerrak",
    "Norwegian Sea": "Mar de Noruega",
    "Ligurian Sea": "Mar de Liguria",
    "Gulf of Guinea": "Golfo de Guinea",
}

AREAS = OBSERVED_AREAS | {
    name: ("iho-" + re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-"), spanish)
    for name, spanish in ADDITIONAL_NAMES_ES.items()
}
